### ISSUE TITLE
И где код? :)

### ISSUE THREAD

**Issue by KarelWintersky** [YakovL/MainTiddlyServer#1]
сабж

**Comment by YakovL** [comment]
Будет в течение недели-другой :) Сейчас окончательно дочищу от вещей, которые не хочу класть в git, протестирую некоторые заявленные вещи (в первую очередь поддержку TW 2.6.5) и выкачу.

**Comment by YakovL** [comment]
Старые версии, впрочем, доступны в https://groups.google.com/forum/#!topic/tiddlywikiclassic/Eb48yQBof5c

**Comment by KarelWintersky** [comment]
ой да, говнокод жуткий.

**Comment by YakovL** [comment]
:D ну всё-таки принципиального улучшения стиля ожидать не стоит, я больше добавляю фичи, чем рефакторю (последнее в основном по мере необходимости), а переписывать с нуля нет ни времени, ни достаточного знания best practices. Если будут пул-реквесты/рекомендации по улучшению, всегда пожалуйста

**Comment by KarelWintersky** [comment]
@YakovL у меня такой вопрос :)

Ты выложил в репо tiddlywiki сырцы tiddlywiki classic (в релизы) и собранный файл в гуглогруппу. 

А ты можешь написать инструкцию о том, как его собирать (cook)? 

Последний раз я пробовал собирать tiddlywiki по старой инструкции год назад и оно нихрена не заработало. Ни под виндой, ни под юнихом. Jeremy на ишью по этой теме сказал, что "у него все прекрасно работает, чужие проблемы он решать не будет и послал меня в гуглогруппы". В гуглогруппах решения не нашлось.

**Comment by YakovL** [comment]
Смотри, документация сборки лежит тут: https://github.com/TiddlyWiki/tiddlywiki.com/

Я существенно обновил структуру, теперь она гораздо ближе к актуальной, но ряд деталей ещё надо прописать. Если чего-то будет непонятно, можешь уточнять, дополню (это в любом случае есть в планах, но до сих пор особо желающих собрать из сорцов не было, поэтому пока на первом месте были выпуск MTS и некоторые другие вещи ближе к конечным пользователям). Одно "но": я собирал только под виндой, так что с документацией под nix-ы могут быть более серьёзные проблемы.

К слову, почему бы не обсуждать это в гуглогруппе? Можно [там](https://groups.google.com/forum/#!forum/tiddlywikiclassic) спросить, я отвечаю более-менее на все посты (хотя иногда с большими задержками). Ну и да, есть [длинный тред в Dev](https://groups.google.com/forum/#!topic/tiddlywikidev/xVZhedaXnS8), там я спрашивал про разные детали и что-то потом резюмировал, но там многабукаф. А то тут вообще issue про MTS, получается чуток оффтопик ;) Можно конкретные проблемы описывать [тут](https://github.com/YakovL/tiddlywiki.com), кстати.

**Comment by YakovL** [comment]
PS а так я планирую поприкреплять к релизам готовые файлы.. только вот нынешние инструменты сборки, боюсь, могут не сработать с предыдущими версиями – или по крайней мере их надо слегка адаптировать.

**Comment by KarelWintersky** [comment]
Я твое мыло не нашел, написал сюда ;)

А в гугглогруппах... хм, у меня не настолько хорошо с английским, чтоыб писать пространные тексты :(

**Comment by YakovL** [comment]
Оки. Если что, пиши на yakov-litvin-public@rambler.ru (сообщение сотру, чтобы почта просто так не отсвечивала, рамблер и так не очень хорошо ловит спам)

**Comment by YakovL** [comment]
Первый релиз закоммитил :)
