### ISSUE TITLE
Prevent warnings from DOMDocument::loadHTML

### ISSUE THREAD

**Issue by YakovL** [YakovL/MainTiddlyServer#11]
As @visick has [reported](https://github.com/YakovL/MainTiddlyServer/issues/10#issuecomment-1951462308), _in some cases_ (granulated) saving reports

    Error while saving. Server:
    Warning: DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 1 in /(path)/index.php on line 1202

while saving actually succeeds, including for an empty TW 2.10.0 (**are the line numbers in the warning exactly these in that case?**).

Currently, I have failed to reproduce this (even with `error_reporting(E_ALL);`), so we need to gather more details:

* OS and version
* PHP version
* MTS code (how is it different from the [latest dev version](https://github.com/YakovL/MainTiddlyServer/blob/ebe97b5f3b546927aff15504cdc0d49c8b6b251a/index.php))

Jon:

> I dug into this a little more and found that `DOMDocument::loadHTML()` uses an HTML 4 parser and differences in HTML 5 can cause it to report errors: https://www.php.net/manual/en/domdocument.loadhtml.php
> 
> As suggested on that page, I added `LIBXML_NOERROR` to line 1202 in MTS index.php to give HTML 5 compatibility:
> 
> `$doc = new DOMDocument(); $doc->LoadHTML('<html><body>'.$tiddlerText.'</body></html>', LIBXML_NOERROR);`
> 
> That got rid of the warning and all is working fine now when the TW is saved.

I suspect that `LIBXML_NOWARNING` would be more proper, but suppressing errors and warnings is not the best idea anyway, it's probably better to use [libxml_use_internal_errors](https://www.php.net/manual/en/function.libxml-use-internal-errors.php) for that. Finally, it's useful to understand which bit of TW 2.10.0 causes the warning and if there's an alternative parser for HTML5.

For any solution, should check PHP versions support and do regression testing (at least @ Android).

**Comment by visick** [comment]
OK, downloaded fresh MTS from dev branch, fresh empty TW 2.10.1 I do not get any issues or warnings with this combination. Not sure about the previous experience, but seems non-reproducible. I should say that I'm running this on a hosted server and don't have full control over the PHP setup...

Thanks!

**Comment by YakovL** [comment]
Right, thanks, feel free to reopen if you find a reproducible setup (closing for now)
