### ISSUE TITLE
Throws error with TWc core 2.9.3

### ISSUE THREAD

**Issue by rcedward** [YakovL/MainTiddlyServer#3]
Bumping version check in index.php _appears_ to allow to work properly in my very limited testing

TWc served from RPi Linux 5.15.56-v7l+ #1575 SMP Fri Jul 22 20:29:46 BST 2022 armv7l GNU/Linux
clients are running MacOS Monterey; iOS 15.6.1

**Comment by YakovL** [comment]
Hi @rcedward could you clarify what is the _issue_ here? MTS 1.7.0 (released 12 days before this issue; I haven't announced it in a separate thread in Google Groups though) has the supported TW version bumped to 2.9.3. Have you missed it (MTS 1.7.0) and wanted to suggest the bump?

**Comment by rcedward** [comment]
Thanks, Yakov. Sorry for the delayed reply — I just found this email in my spam folder.

Just after I’d upgraded my TWc to 2.9.3 and discovered the issue with MTS, the most recent version of MTS I saw at github was 1.6.x. Maybe I had a caching issue or something? But if 1.7 is out and is aligned with TWc then my issue is moot.

Cheers!

**Comment by rcedward** [comment]
User error

**Comment by rcedward** [comment]
NB: https://yakovl.github.io/MainTiddlyServer/index.html <https://yakovl.github.io/MainTiddlyServer/index.html> states "Currently versions 2.6.5-2.9.1 of TWc are supported…” Text should be updated.

**Comment by YakovL** [comment]
Right, I see, no problem. I hope in one of the next versions I'll implement MTS upgrade autodetection (and may be even self-upgrading) so this won't be and issue anyway. And thanks for the catch (the outdated text in index.html), I'll deal with that too. Best regards, Yakov.
07.09.2022, 17:07, rcedward < ***@***.*** ***@***.*** >
